CarShare/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using CarShare.Data;
using CarShare.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
namespace CarShare.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        ApplicationDbContext _db;
        private IHttpContextAccessor _hca;

        public UserController(ApplicationDbContext db, IHttpContextAccessor hca)
        {
            _db = db;
            _hca = hca;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            //Console.WriteLine("From Index");
            //Console.WriteLine(User.Identity);
            return View();
        }

        public IActionResult CarHireBrowse()
        {
            return View();
        }

        public IActionResult CarHire(int Id, string PickUpTime, string DropOffTime)
        {
            Car car = _db.Cars.Where(c => c.Id == Id).FirstOrDefault();
            ViewBag.car = car;

            // Image
            Image img = _db.Images.SingleOrDefault(i => i.Id == car.ImageId);
            ViewBag.ImageTitle = img.Title;
            ViewBag.ImageUrl = string.Format("data:image/jgp;base64,{0}", Convert.ToBase64String(img.Data));

            // Parking lot details
            ParkingLot pl = _db.ParkingLots.Where(p => p.Id == car.ParkingLotId).FirstOrDefault();
            ViewBag.plLatitude = pl.Latitude;
            ViewBag.plLongitude = pl.Longitude;
            ViewBag.plAddress = pl.Address;

            // misc
            ViewBag.PickUpTime = PickUpTime;
            ViewBag.DropOffTime = DropOffTime;

            return View();
        }

        public IActionResult HireCarSubmit(int Id, string PickUpTime, string DropOffTime)
        {
            Car car = _db.Cars.Where(c => c.Id == Id).FirstOrDefault();
            ParkingLot pl = _db.ParkingLots.Where(p => p.Id == car.ParkingLotId).FirstOrDefault();
            DateTime pickUpDateTime = DateTime.Parse(PickUpTime);
            DateTime dropOffDateTime = DateTime.Parse(DropOffTime);
            TimeSpan duration = dropOffDateTime.Subtract(pickUpDateTime);

            CarHistory history = new CarHistory()
            {
                HireTime = pickUpDateTime,
                InitialLongitude = pl.Longitude,
                InitialLatitude = pl.Latitude,
                ReturnedLongitude = -1,
                ReturnedLatitude = -1,
                ReturnedTime = dropOffDateTime,
                Status = HireStatus.Planned,
                UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                CarId = car.Id
            };

            _db.CarHistory.Add(history);
            _db.SaveChanges();

            return View("CarHireConfirmation");
        }
    }
}

CarShare/Controllers/UserhistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarShare.Data;
using CarShare.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using System.Security.Claims;

namespace CarShare.Controllers
{
    public class UserhistoryController : Controller
    {
        ApplicationDbContext _db;

        public UserhistoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var carHistories = _db.CarHistory.Where(a => a.UserId == userId).OrderBy(a => a.HireTime);
            var cars = _db.Cars.ToList<Car>();

            var query = from car in cars
                        join history in carHistories on car equals history.Car orderby history.HireTime
                        select new CarHistoryUserViewModel()
                        {
                            Registration = car.Registration,
                            Description = car.Description,
                            ReturnedTime = history.ReturnedTime,
                            HireTime = history.HireTime,
                            ReturnAddress = _db.ParkingLots.Where(pl => pl.Id == car.ParkingLotId).FirstOrDefault().Address,
                            InitialLongitude = history.InitialLongitude,
                            InitialLatitude = history.InitialLatitude,
                            ReturnedLongitude = history.ReturnedLongitude,
                            ReturnedLatitude = history.ReturnedLatitude,
                            Status = history.Status
                        };

            const int pageSize = 50;
            ViewBag.userId = userId;
            var pagedList1 = await query.ToPagedListAsync(page, pageSize);

            return View(pagedList1);

           
        }
    }
}

CarShare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UrbanHire</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <link rel="stylesheet" href="~/css/jquery-ui.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Admin"))
                    {
                        <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">UrbanHire</a>

                    }
                    else
                    {
                        <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Index">UrbanHire</a>
                    }

                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UrbanHire</a>
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @*Authenticates the Admin. If authorised the admin can view the Admin Index page and the UserManagement page*@
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Dashboard</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="UserManagement">User Management</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="FleetManagement">Fleet Management</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ParkingLotManagement">Parking Lot Management</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Dashboard</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Userhistory" asp-action="Index">History</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="CarHireBrowse">Hire Now</a>
                                </li>
                            }

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>


                        }
                            @if (User.Identity.IsAuthenticated == false)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - Urban Hire - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>